language: python
python:
- '3.4'
install:
  - pip install virtualenv
  - virtualenv venv
  - . venv/bin/activate
  - pip install -r requirements.txt
script:
  - py.test test/ --doctest-modules -v --cov src --cov-report term-missing
after_success:
  - coveralls
after_script:
  - deactivate
